### ISSUE TITLE
Profile model

### ISSUE THREAD

**Issue by cturbelin** [influenzanet/api#1]
Profile model seems to contain first & last name : is this for all users or is this just for tests ?

**Comment by phev8** [comment]
It would be an optional field for every user, used for personalisation purposes. If available, notifications could be sent with personalised greeting, and eventually for later social features. 
This profile information is NOT stored together with survey data and should NOT be accessible for researchers - only for the user herself.

**Comment by cturbelin** [comment]
Yes, I understand. There is a balance to find between the user friendliness of the system and the privacy. 

If we collect information labelled "first name" and "last name" we implicitly ask for this kind of information. I mean it's not exactly the same as asking for a nick name, if you ask for real name many users will give it (they are not fully aware about privacy implication but we have to). As we don't need it to reach the goal of the project we should be very careful to collect this kind of information.

They are not stored with, but they belong to the same system, probably managed by the same team so the separation is not perfect. Finally the only way to be secured is to reduce as much as possible the information we collect.

**Comment by phev8** [comment]
Profile model was changed to include only nickname
